import { Match } from '../types';

export const fetchDailyMatches = async (): Promise<Match[]> => {
  try {
    // Fetch the static JSON file generated by the GitHub Action
    const response = await fetch('/matches.json');

    if (!response.ok) {
      throw new Error(`Failed to fetch matches: ${response.statusText}`);
    }

    const matches: Match[] = await response.json();

    // Basic validation
    if (!Array.isArray(matches)) {
      throw new Error("Invalid format: Expected an array of matches");
    }

    return matches;

  } catch (error) {
    console.error("Error fetching daily matches:", error);
    throw error;
  }
};