import { Match } from '../types';

export const fetchDailyMatches = async (): Promise<Match[]> => {
  try {
    // Fetch the static JSON file generated by the GitHub Action
    // Fetch the static JSON file generated by the GitHub Action
    // Use import.meta.env.BASE_URL to handle the subdirectory on GitHub Pages
    const baseUrl = import.meta.env.BASE_URL.endsWith('/')
      ? import.meta.env.BASE_URL
      : `${import.meta.env.BASE_URL}/`;

    const response = await fetch(`${baseUrl}matches.json`);

    if (!response.ok) {
      throw new Error(`Failed to fetch matches: ${response.statusText}`);
    }

    const matches: Match[] = await response.json();

    // Basic validation
    if (!Array.isArray(matches)) {
      throw new Error("Invalid format: Expected an array of matches");
    }

    return matches;

  } catch (error) {
    console.error("Error fetching daily matches:", error);
    throw error;
  }
};